PsycheFoundation/psyche

- psyche-book/src/enduser/authentication.md
- psyche-book/src/explain/rewards.md
Fix links to smart contracts in the `psyche-book`
> fix: book broken links

- shared/coordinator/src/coordinator.rs
Some modifications were done to this function at some time and some legacy and redundant code was left. This PR removes the redundant code and also fixes some lines that could bring a bug in some particular situations.
Basically, there was some program logic to check if we should change the checkpoint to `Hub`; this should happen if there are no peers from the previous epoch joining in the new one. This logic was repeated two times, so it was removed.
Also, unhealthy clients were kicked *after* the logic for changing checkpoint, so in some very edge cases the checkpoint could have not correctly set to `Hub` when it should.
Closes #51
> fix: `tick_waiting_for_members` function

- website/frontend/src/components/ContributeCompute.tsx
firefox works fine without it, but chromium doesn't. weird!
> frontend: fix: rank table width in chromium

- architectures/centralized/testing/src/client.rs
- architectures/centralized/testing/src/test_utils.rs
- architectures/centralized/testing/tests/integration_tests.rs
- architectures/decentralized/testing/tests/integration_tests.rs
- shared/client/src/state/steps.rs
Until now, when a client joined in Warmup, it started downloading the model either via p2p or hub, but it was not yet allowed to participate in the upcoming epoch.
Additionally, if everybody left while in Warmup, when another client joined, it would request parameters to peers that are no longer in the run.
This PR handles all these bugs. The fix is straightforward, clients that join in Warmup have to wait until the next epoch to download the model & start training
> fix: warmup run state related bugs

- architectures/decentralized/solana-tooling/src/get_accounts.rs
- architectures/decentralized/solana-tooling/tests/suites/memnet_treasurer_full_epoch.rs
- architectures/decentralized/solana-treasurer/programs/solana-treasurer/src/logic/participant_claim.rs
- architectures/decentralized/solana-treasurer/programs/solana-treasurer/src/logic/run_create.rs
- architectures/decentralized/solana-treasurer/programs/solana-treasurer/src/state/run.rs
This is a nit to simplify the logic for the treasurer, where we used to have the coordinator set a reward rate for each epoch then the treasurer would also set a reward rate "per-point".
Then the reward would be: `collateral = point_reward * collateral_per_point`. This is unecessary as of right now as the coordinator can simply specify whatever rate it wants and the treasurer can just distribute one collateral per point.
> nit: treasurer: remove the need for collateral_amount_per_earned_point

- shared/eval/src/lib.rs
- shared/eval/src/tasks/boolq.rs
- shared/eval/src/tasks/mod.rs
- shared/eval/src/tasks/piqa.rs
Add the PIQA benchmark to evaluate the model
* Benchmark results:
```
cargo run --release --example evaluate -- --tasks piqa --model TinyLlama/TinyLlama-1.1B-Chat-v0.1
PIQA: {"acc": 0.691512513601741, "acc_norm": 0.6953210010881393}
cargo run --release --example evaluate -- --tasks piqa --model TinyLlama/TinyLlama-1.1B-Chat-v0.4
PIQA: {"acc": 0.7105549510337323, "acc_norm": 0.7138193688792165}
```
* [Benchmark results for comparation](https://github.com/jzhang38/TinyLlama/blob/main/EVAL.md)
* [paper](https://arxiv.org/abs/1911.11641)
* [llm_eval](https://github.com/EleutherAI/lm-evaluation-harness/blob/7aaceeec2e7b686d95d0e55b43af641dc2484b4a/lm_eval/tasks/piqa/piqa.yaml)
> Add PIQA model evaluation

- Cargo.lock
- Cargo.toml
- shared/network/src/lib.rs
Instead of adding blob-level timeouts in iroh, we tweaked some configuration parameters to ensure that blob downloads time out at the connection level if no progress is made. These new settings apply a 5 second idle timeout and abort each failed download attempt immediately, so we can trigger our own retry logic rather than relying on iroh’s built-in retries.
> Update idle timeout and retry configs

- Cargo.toml
- shared/network/src/lib.rs
- shared/network/src/test.rs
New test setup for the network module introduces two nodes, a sender and a receiver, used to validate blob download failure behavior under crash conditions with a 1 GB blob:
* **Test 1**: Verifies that a `DownloadFailed` event is received if the sender crashes before the receiver begins downloading the blob.
* **Test 2**: Verifies that a `DownloadFailed` event is received if the sender crashes mid-transfer while sharing the blob.
> test: new tests for network module

- shared/eval/src/tasks/boolq.rs
- shared/eval/src/tasks/mmlu.rs
- shared/eval/src/tasks/openbookqa.rs
After reviewing the [lm_eval](https://github.com/EleutherAI/lm-evaluation-harness) evaluations implementation, I found we were having some discrepancies in the inputs we pass to the model in some evaluations
* Modify the prompt we pass to the model. [See lm_eval repo](https://github.com/EleutherAI/lm-evaluation-harness/blob/8bc4afff22e73995883de41018388428e39f8a92/lm_eval/tasks/mmlu/flan_cot_zeroshot/mmlu_computer_security.yaml)  
* Modify the dataset used. [See lm_eval repo](https://github.com/EleutherAI/lm-evaluation-harness/blob/main/lm_eval/tasks/super_glue/boolq/default.yaml)
* Modify the dataset used. [See lm_eval repo](https://github.com/EleutherAI/lm-evaluation-harness/blob/main/lm_eval/tasks/openbookqa/openbookqa.yaml)
```
BoolQ: {"acc_norm": 0.5694189602446483, "acc": …
```
> Fixes in MMLU, BoolQ and OpenBookQA evaluations

- architectures/decentralized/solana-client/src/app.rs
- architectures/decentralized/solana-client/src/backend.rs
- architectures/decentralized/solana-client/src/retry.rs
- architectures/decentralized/solana-coordinator/programs/solana-coordinator/src/instance_state.rs
- architectures/decentralized/solana-coordinator/programs/solana-coordinator/src/program_error.rs
- architectures/decentralized/testing/tests/integration_tests.rs
Closes #48
Not too important for a real case scenario, but for small training runs made for testing this is a quality of life feature.
We noticed that when there are more clients than the number of global batch size set in the config, some client is not assigned any batch and eventually is kicked. Not only this, but the coordinator ends in some weird state and other clients are kicked too.
This PR adds a small check when a new client joins; if the global batch size is equal to the number of clients present in the run, then an error is raised and the new client doesn't join the run
> feat: return error if number of clients exceeds number of global batches to assign

- architectures/decentralized/solana-client/src/main.rs
If the run is paused the duplicate key check may hit, but we'll clear out all clients coming out of paused (so we're still able to join)
> bug: skip duplicate key check if run is paused

- architectures/decentralized/solana-coordinator/programs/solana-coordinator/src/client.rs
- shared/coordinator/src/coordinator.rs
- shared/core/src/fixed_string.rs
- shared/core/src/fixed_vec.rs
- shared/core/src/small_boolean.rs
We use bytemuck for serialization/deserialization, meaning that we use the Raw RAM layout for serialization. The RAM layout depends on the `Repr()`.
One big No-no here is that the `Repr(Rust)` does NOT guarantee anything layout wise and its actual behaviour is undefined (although compiler internals as of today make it somewhat predictable for simple cases).
This means that `Repr(Rust)` is BY DEFINITION not cross-platform (aka typescript incompatible for example)
This PR hunts down the last few remaining forgotten `Repr(Rust)` but with most importantly: THIS PR DOES NOT CHANGE THE BINARY LAYOUT, just translate to the non `Repr(Rust)` current equivalent of the current behaviour.
> fix: hunting down remaining Repr(Rust)

- shared/eval/examples/evaluate.rs
- shared/eval/src/harness.rs
After fix:
`lm-eval` ref:
```
hf (pretrained=meta-llama/Meta-Llama-3-8B), gen_kwargs: (None), limit: None, num_fewshot: None, batch_size: 8
|    Tasks    |Version|Filter|n-shot| Metric |   |Value |   |Stderr|
|-------------|------:|------|-----:|--------|---|-----:|---|-----:|
|arc_challenge|      1|none  |     0|acc     |↑  |0.5043|±  |0.0146|
|             |       |none  |     0|acc_norm|↑  |0.5316|±  |0.0146|
|arc_easy     |      1|none  |     0|acc     |↑  |0.8005|±  |0.0082|
|             |       |none  |     0|acc_norm|↑  |0.7782|±  |0.0085|
|boolq        |      2|none  |     0|acc     |↑  |0.8107|±  |0.0069|
|hellaswag    |      1|none  |     0|acc     |↑  |0.6005|±  |0.0049|
|             |       |none  |     0|acc_norm|↑  |0.7915|±  |0.0041|
|openbookqa   |      1|none  | …
```
> fix: add space before evaluating answers for log-likelihood evals

- shared/client/src/client.rs
- shared/network/src/download_manager.rs
- shared/network/src/lib.rs
- shared/network/src/p2p_model_sharing.rs
This PR makes some improvements on the model sharing retries and add some logs to actually check the errors we're getting about `No providers found` trying to download paramaters from other peers.
Specifically the improvements are:
- Avoid locking the client loop trying to retry a failed download.
- Use the `peer_cycle` and the `errored_peers` as a shared result. That way we avoid using different peers states for the retry and the main paramter sharing logic.
> P2P retry model sharing improvements

- shared/client/src/lib.rs
- shared/client/src/state/init.rs
The application will continue and we log an error to the console, in the future we might want to retry the operating in a separate thread in the background or similar, but for now this is the simplest solution.
Originally we tried to do the retry logic but we had to made some functions async and it got messy really quickly, we can take a look at it in the future if we deem it important.
Solves #98
> Do not panic on wandb failure

- architectures/decentralized/solana-coordinator/programs/solana-coordinator/src/instance_state.rs
- architectures/decentralized/solana-coordinator/programs/solana-coordinator/src/lib.rs
- architectures/decentralized/solana-coordinator/programs/solana-coordinator/src/logic/free_coordinator.rs
- architectures/decentralized/solana-coordinator/programs/solana-coordinator/src/logic/init_coordinator.rs
- architectures/decentralized/solana-coordinator/programs/solana-coordinator/src/logic/join_run.rs
- architectures/decentralized/solana-tooling/src/process_coordinator_instructions.rs
- architectures/decentralized/solana-tooling/tests/suites/memnet_coordinator_full_round.rs
- architectures/decentralized/solana-tooling/tests/suites/memnet_coordinator_rewards.rs
- architectures/decentralized/solana-tooling/tests/suites/memnet_treasurer_full_epoch.rs
- architectures/decentralized/solana-tooling/tests/suites/mod.rs
- shared/coordinator/src/coordinator.rs
- shared/coordinator/src/lib.rs
Giving another shot to fixing the reward distribution logic from the revert PR: https://github.com/PsycheFoundation/psyche/pull/116
Retrying by not using a `HashSet` during reward distribution but instead keeping original client ordering when initiating the epoch's client list (so that the reward distribution can just do a sequential scan on the client list)
> fix: retry fixing reward distribution

- shared/client/src/client.rs
- shared/network/src/lib.rs
- shared/network/src/p2p_model_sharing.rs
Since we're hitting the `No provider nodes found` error fairly often, we’re adjusting how the retry logic works for downloading model parameters. Right now, the client gives up on a parameter after three consecutive failures, regardless of how many different peers were involved. It's a common situation to hit three failing peers in a row, so we need a more resilient approach.
The updated logic now distinguishes between two failure cases:
1. **Failure when requesting the blob ticket** – meaning the connection via the iroh protocol couldn’t even be established or there was an error generating the blob ticket for a parameter
2. **Failure mid-download** – where we successfully got the blob ticket, but the download fails afterward (often with the `No provider nodes found` error).
The new …
> New retry logic for model sharing process over P2P

- architectures/centralized/client/src/app.rs
- architectures/decentralized/solana-client/src/app.rs
- shared/client/src/client.rs
- shared/metrics/src/lib.rs
- shared/network/examples/bandwidth_test.rs
- shared/network/src/lib.rs
- shared/network/src/test.rs
we cloned it a few places, but killed the shared task when any clone was dropped.
now it's unclonable and we pass it around as an Arc everywhere
> metrics: fix metrics server dying

- garnix.yaml
it requires impure, so can't possibly build.
> ci: don't build the psyche solana test docker package

- architectures/centralized/server/src/main.rs
- justfile
- scripts/train-solana-test.sh
- shared/client/src/cli.rs
- shared/client/src/client.rs
- shared/client/src/state/init.rs
- shared/client/src/state/stats.rs
- shared/client/src/state/steps.rs
- shared/metrics/src/lib.rs
- shared/network/src/lib.rs
- telemetry/README.md
- telemetry/docker-compose.yml
- telemetry/grafana/dashboards/clients_dashboard.json
- telemetry/grafana/provisioning/dashboards/dashboard.yaml
- telemetry/grafana/provisioning/datasources/datasources.yaml
- telemetry/loki-config.yaml
- telemetry/otel-collector-config.yaml
- telemetry/prometheus.yml
The idea of this PR is to add a custom dashboard that can be useful as a starting point to monitor the state of each client more easily.
In the dashboard, there is a dropdown to select each of the connected clients:
Once a client is selected, you can see three visualization rows.
The first one, shows a couple of general metrics of the client state, like the current step, the number of gossip neighbors and a plot visualizing when the client finished training in a step:
The second one shows some visualizations for the p2p model sharing state of the client, mostly relevant when the client joins a run and requests the parameters to other peers:
The third one shows the logs for that client:
---
A readme has been also added for spawning the telemetry stack locally in `/telemetry/README.md`. …
> local telemetry, new metrics, and cardinality reduction

- architectures/decentralized/solana-client/src/main.rs
When a run is first created its in the `Uninitialized` state not `Paused`, but we still want to be able to do preload then
> allow preload during uninitialized state

- shared/data-provider/src/preprocessed.rs
We need to loop preprocessed data forever, otherwise we error at the end of one epoch
> bug: loop preprocessed data forever

- shared/core/src/running_average.rs
wrong comparison direction for minimum samples
> fix running average min samples calc (backward comparison)

- python/python/psyche/models/hf_transformers.py
use attn_implementation='flash_attention_2' 
closes #199 
running the cmd now return correct results 
```
~/psyche$ nix develop .#dev-python --command cargo run --features parallelism,python --example train -- --model NousResearch/Meta-Llama-3.1-8B --data-path ./data/Hermes-3-Preprocessed-Llama3/data --data-parallelism 8 --micro-batch 1 --sequence-length 4096 --beta2 0.999 --total-batch 128 --learning-rate 0.000007 --warmup-steps 300 --weight-decay 0.01 --total-steps 2900 --python
2025-08-11T21:27:11.800738Z  INFO train: step: 1, duration: 15.14, loss: 0.8877
2025-08-11T21:27:23.953044Z  INFO train: step: 2, duration: 12.15, loss: 0.8913
2025-08-11T21:27:36.147032Z  INFO train: step: 3, duration: 12.19, loss: 0.9093
```
> use flash attention 2

- architectures/decentralized/solana-client/src/backend.rs
- architectures/decentralized/solana-client/src/command/create_run.rs
- architectures/decentralized/solana-client/src/command/json_dump_run.rs
- architectures/decentralized/solana-client/src/command/json_dump_user.rs
- architectures/decentralized/solana-client/src/command/json_info_dump.rs
- architectures/decentralized/solana-client/src/command/mod.rs
- architectures/decentralized/solana-client/src/command/set_future_epoch_rates.rs
- architectures/decentralized/solana-client/src/command/treasurer_claim_rewards.rs
- architectures/decentralized/solana-client/src/command/treasurer_top_up_rewards.rs
- architectures/decentralized/solana-client/src/main.rs
- psyche-book/src/enduser/create-run.md
Follow-up on feedbacks made about the CLI, small improvements all around.
Note: Adds a `json-dump-user` command (to go with `json-dump-run`)
Addresses:
- https://github.com/PsycheFoundation/psyche/issues/247
- https://github.com/PsycheFoundation/psyche/issues/246
- https://github.com/PsycheFoundation/psyche/issues/22
Also adds a new CLI command to dump information about a user client in particular (within a run). Separate from the command to dump information about the run itself.
> feat: implementing feedbacks on the CLI

- shared/eval/src/harness.rs
- shared/eval/src/tasks/arc.rs
- shared/eval/src/tasks/boolq.rs
- shared/eval/src/tasks/hellaswag.rs
- shared/eval/src/tasks/mmlu.rs
- shared/eval/src/tasks/openbookqa.rs
- shared/eval/src/tasks/piqa.rs
- shared/eval/src/traits.rs
If you look at the previous code currently in main apparently we do not use `context` for anything, in this PR I attempted to use it in the prompt so that the model gets the actual fewshot context alongside the prompt and options.
We also try to use fewshot from the same category as the question.
I've run some simple benchmarks and it doesn't seem to improve too much if at all, depending on the task, but it seems weird to not use the context for anything. Currently in `main` adding fewshots does not modify the accuracy at all, and now they do.
Closes #223
> evals: improve fewshot

- Cargo.lock
- python/extension-impl/Cargo.toml
- python/extension-impl/src/extension.rs
- python/python/psyche/sidecar/__main__.py
- shared/modeling/src/python_distributed_causal_lm.rs
- shared/modeling/src/python_distributed_trainer.rs
This fixes an extremely difficult to track down bug where some Python runs would inexplicably (but reproducibly) stall when using FSDPv2. Although the reason is unclear, the error came down to the c10d store server in the Rust process not properly updating Python clients. Disabling the uvloop backend in Python and using the legacy direct socket backend fixes it. I assume it's some evil interaction between the Rust system and uvloop
> bug: don't use uvloop for c10d store

- Cargo.lock
- Cargo.toml
- shared/network/src/serialized_distro.rs
updated tch-rs to use the new non-device-passing pin fn calls
> get rid of pin deprecation warnings

- shared/client/src/state/evals.rs
- shared/eval/examples/evaluate.rs
- shared/eval/src/harness.rs
- shared/eval/src/lib.rs
When running the evaluation example with DP>1 the progress bars were duplicated and not being updated.
Now we just show a single bar with the shared progress between threads.
Closes #282
> evals: fix progress bars when DP>1

- nix/docker.nix
Just add `LOGNAME`, `TORCHINDUCTOR_CACHE_DIR`, `TRITON_LIBCUDA_PATH` and `PYTHONUNBUFFERED` env vars in the docker image when building it so that we don't have to pass them when running it
> feat(docker): add env vars to client image needed for triton config
