PsycheFoundation/psyche

shared/eval/examples/evaluate.rs, shared/eval/src/lib.rs, shared/eval/src/tasks/boolq.rs, shared/eval/src/tasks/mod.rs
Add the BoolQ benchmark to evaluate the model
See [paper](https://arxiv.org/abs/1905.10044)
=> Add BoolQ model evaluation

shared/eval/src/tasks/boolq.rs
now matches `lm-evaluation-harness`
=> fix: change boolq to match lm-evaluation-harness

shared/client/src/client.rs, shared/network/src/lib.rs
previously, we only checked our connection to the gossip network when we got a new state from the coordinator.
this meant that a network disconnection in the Warmup step would not be repaired until Warmup ended.
to fix this, we simply check our gossip connections every 10s & re-bootstrap as much as needed if we're offline.
=> fix: reconnect to the gossip network if we have no peers

website/frontend/src/components/ContributeCompute.tsx, website/frontend/src/components/GiveMoney.tsx, website/frontend/src/fakeData.ts
clarifies why further donations are not possible, includes a discord link.
=> frontend: show "pool is full" text

Cargo.lock, architectures/decentralized/solana-client/Cargo.toml, architectures/decentralized/solana-client/src/main.rs, psyche-book/src/enduser/join-run.md
also improve can-join with additional checks
=> solana client: add model predownload

Cargo.lock, architectures/centralized/client/src/app.rs, architectures/centralized/client/src/main.rs, architectures/centralized/local-testnet/src/main.rs, architectures/centralized/testing/src/test_utils.rs, architectures/decentralized/solana-client/src/app.rs, architectures/decentralized/solana-client/src/main.rs, shared/client/src/cli.rs, shared/metrics/Cargo.toml, shared/metrics/src/lib.rs, shared/network/examples/bandwidth_test.rs, shared/network/src/test.rs
Quick hackish impl for now, probably we can think a better approach later
Merge #137 first as I've already rebased that onto this branch.
Closes #133
=> TCP Metrics Endpoint

Cargo.lock, architectures/centralized/client/src/app.rs, architectures/centralized/client/src/main.rs, architectures/centralized/local-testnet/src/main.rs, architectures/centralized/testing/src/test_utils.rs, architectures/decentralized/solana-client/src/app.rs, architectures/decentralized/solana-client/src/main.rs, shared/client/src/cli.rs, shared/client/src/client.rs, shared/metrics/Cargo.toml, shared/metrics/src/lib.rs, shared/network/examples/bandwidth_test.rs, shared/network/src/test.rs
=> metrics: local server, reduce cardinality on metrics

architectures/decentralized/solana-coordinator/default.nix, architectures/decentralized/solana-mining-pool/default.nix, flake.lock, flake.nix, nix/checks.nix, nix/devShell.nix, nix/formatter.nix, nix/lib.nix, nix/nixosModules.nix, nix/nixpkgs.nix, nix/packages.nix, nix/pkgs.nix, psyche-book/default.nix, website/backend/default.nix, website/common.nix, website/frontend/default.nix, website/shared/default.nix, website/wasm/default.nix, website/wasm/fixup.sh
hopefully some good work on that nix clean up you wanted @arilotter :D
i did my best to also split up the commits.
quite a bit of my work really ended up being on cohesion of the nix rather then the packages themselves. they are quite well managed by crane :P
=> nix: housekeeping

scripts/push-new-model.py
Tentative implementation, not tested for runtime errors...
=> Add mitchell model init to Deepseek v3 Dense MLA models

architectures/decentralized/solana-authorizer/README.md, architectures/decentralized/solana-treasurer/README.md, psyche-book/src/enduser/create-run.md
Small refresh for the documentation related to how to create a treasurer backed coordinator run.
=> chore: refresh docs for treasurer and CLI

shared/metrics/src/lib.rs
a histogram doesn't make sense here
=> metrics: switch GPU usage to gauge

architectures/decentralized/solana-client/src/main.rs, shared/client/src/cli.rs
=> add --predownload-eval-tasks

Cargo.lock, Cargo.toml, nix/nixpkgs.nix
``cargo run --features parallelism --example train -- --tensor-parallelism 8 --distro` will crash with `Segmentation fault: 11`. reverting til we can fix.
=> revert torch to 2.7.0

architectures/centralized/client/Cargo.toml, architectures/centralized/local-testnet/Cargo.toml, architectures/centralized/server/Cargo.toml, architectures/decentralized/solana-client/Cargo.toml, docker/train_entrypoint.sh, nix/checks.nix, nix/lib.nix, psyche-book/default.nix, python/Cargo.toml, python/default.nix, python/extension-impl/Cargo.toml, python/extension-impl/src/extension.rs, python/extension-impl/src/lib.rs, python/src/lib.rs, shared/client/Cargo.toml, shared/modeling/Cargo.toml, tools/rust-tools/expand-distro/Cargo.toml
Fixes Python support in the Docker container, pulled from #234
=> fix: python support in docker container

nix/docker.nix, nix/packages.nix
put application code in its own layer, so changing our code doesn't cause a massive layer push/pull! :)
=> nix docker: reverse layer order

Cargo.lock, Cargo.toml, nix/nixpkgs.nix, nix/nvshmem.nix, shared/modeling/src/lib.rs, shared/network/src/serialized_distro.rs
correctly rebuilt the tch-rs bindings this time, hopefully avoiding a segfault.
=> update to torch 2.9.0 nightly

shared/client/src/state/stats.rs, shared/coordinator/src/coordinator.rs
Reverts PsycheFoundation/psyche#224
I think most of this got subsumed into #215 so we can just merge that
=> Revert "Enable WitnessMetadata.prompt_results"

docker/psyche_client_create_run.sh, psyche-book/src/explain/general-workflow.md, psyche-book/src/explain/index.md, shared/network/src/download_manager.rs
=> fix: typos

flake.lock, nix/docker.nix
new garnix cli fixes ci, oopsie!
=> fix macos builds

python/python/psyche/models/hf_transformers.py, python/python/psyche/sidecar/__main__.py, shared/client/src/client.rs, shared/client/src/state/evals.rs, shared/client/src/state/init.rs, shared/client/src/state/prompt.rs, shared/client/src/state/stats.rs, shared/modeling/src/python_distributed_causal_lm.rs, shared/modeling/src/python_distributed_trainer.rs, shared/modeling/src/trainer.rs, shared/network/src/lib.rs
Because of some peculiarities with FSDP we need to do a full forward/backward of the model before we can do any inference. This delays evals until we've done a successful training step
=> bug: fix loss divergence when mixing fsdp training and inference

python/python/psyche/dtensor_helpers.py, python/python/psyche/models/hf_transformers.py, shared/modeling/examples/train.rs, shared/modeling/src/python_causal_lm.rs, shared/modeling/src/trainer.rs
this adds TP to python and fixes bug where we were all gathering the whole model to do grad norm clipping
=> feat: python tp

shared/data-provider/examples/README.md, shared/data-provider/examples/http.rs, shared/data-provider/examples/sample-weighted-config.json
Not sure if this is exactly what we wanted but seems to work
For testing I created a bunch of random dummy data
`dd if=/dev/urandom of=~/data/dummy1/000.ds bs=8192 count=1`
and then using `nginx` I started two servers serving the different files
Closes #277
=> example: data provider: WeightedHTTP support
